# Generated by Django 6.0.7 on 2026-08-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authz', '0002_seed_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='relation',
            field=models.CharField(choices=[('can_view', 'Can view'), ('can_edit', 'Can edit'), ('can_delete', 'Can delete'), ('can_admin', 'Full control')], max_length=20),
        ),
    ]
